mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081
lyz:
  jwt:
    # 加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # 有效时长
    expire: 604800
    header: Authorization