# DataSource Config
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/db_myphd?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: admin
  web:
    resources:
      static-locations: file:/usr/local/pdfStore,file:/usr/local/groupFileStore
  mvc:
    static-path-pattern: /**

shiro-redis:
  enabled: true
  redis-manager:
    host: redis:6379